[package]
name = "AzLangInterPretator"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = "3.19.0"
chrono = "0.4.42"
clap = { version = "4.5.48", features = ["derive"] }
color-eyre = "0.6.5"
limit-alloc = "0.1.0"
peekmore = "1.3.0"
thiserror = "2.0.16"
