[package]
name = "AzLang"
version = "0.1.0"
edition = "2024"



[dependencies]
logging = { path = "./crates/logging" }
cli = { path = "./crates/cli"}
interpreter = { path = "./interpreter"}
compiler = { path = "./compiler"}
errors = { path = "./crates/errors"}
