[package]
name = "AzLangOptimized"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
color-eyre = "0.6.5"
clap = { version = "4.5.39", features = ["derive"] }
thiserror = "2.0.12"
peekmore = "1.3.0"
sysinfo = "0.36.1"
limit-alloc = "0.1.0"
