[package]
name = "tester"
version = "0.1.0"
edition = "2024"

[dependencies]
file_system = { path = "../crates/file_system" }
tokenizer = { path = "../crates/tokenizer" }
logging = { path = "../crates/logging" }
parser = { path = "../crates/parser/" }
