[package]
name = "interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
tokenizer = { path = "../crates/tokenizer/" }
errors = { path = "../crates/errors/" }
file_system = { path = "../crates/file_system/" }
logging = { path = "../crates/logging/" }
peekmore = "1.3.0"
