name: Windows Installer (NSIS)

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build AzLang
        run: cargo build --release

      - name: Copy binary to installer folder
        run: |
          copy target\release\azlang.exe installer\azlang.exe

      - name: Build Windows Installer (NSIS)
        uses: joncloud/makensis-action@v4
        with:
          script-file: installer/azlang_installer.nsi

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: AzLang-Windows-Installer
          path: installer/AzLang_Setup.exe
